server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentinfo
    username: studentinfo
    password: md7TCHF5FrayakPW

    # 数据库连接池的配置
    dbcp2:
      min-idle: 5            # 数据库连接池的最小维持连接数
      initial-size: 5        # 初始化提供的连接数
      max-total: 200           # 最大的连接数
      max-wait-millis: 200   # 等待连接获取的最大超时时间

#  redis:
#    host: 127.0.0.1
#    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
