server:
  port: 8081
  servlet:
    session:
      timeout: 120

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentinfo
    username: studentinfo
    password: md7TCHF5FrayakPW

    # 数据库连接池的配置
    dbcp2:
      min-idle: 5            # 数据库连接池的最小维持连接数
      initial-size: 5        # 初始化提供的连接数
      max-total: 200           # 最大的连接数
      max-wait-millis: 200   # 等待连接获取的最大超时时间

  # thymeleaf模板
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#  redis:
#    host: 127.0.0.1
#    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: studentinfo.log
    max-size: 2MB
  level:
    root: info
